model_name: "nomic-ai/gpt4all-j"
revision: "v1.3-groovy"
tokenizer_name: "nomic-ai/gpt4all-j"

# dataset
streaming: false
num_proc: 64
dataset_path: "nomic-ai/cohere-wiki-sbert"
batch_size: 32 
output_path: "synth_qa_pairs"

# generation
max_new_tokens: 75
max_generations: 200000

save_every: 1000


seed: 42