# dataset
streaming: false
num_proc: 64
dataset_path: "squad"
max_length: 1024
batch_size: 32

#index
index_path: "/home/paperspace/gpt4all/gpt4all/index/wiki-cohere-index.bin"
index_database: "nomic-ai/cohere-wiki-sbert"
index_space: "cosine"
index_dim: 384
query_embedding_field: 'question'