# model/tokenizer
model_name: "EleutherAI/pythia-1b"
tokenizer_name: "EleutherAI/pythia-1b"
version: null
gradient_checkpointing: true
save_name: "nomic-ai/lethe"
push_to_hub: false
memory_attn_layer: [9, 12, 15]

# dataset
streaming: false
num_proc: 64
dataset_path: "/home/paperspace/gpt4all/gpt4all/inference/synth_data_combined_174"
max_length: 1024
batch_size: 32
pct_test: 0.05
q_column: "question"
a_column: "answer"
context_column: "text"
num_memories_per_index: 2048
num_neighbors_to_retrieve: 2
num_neighbors_to_store: 1 
mem_chunk_size: 64

# train dynamics
lr: 1.0e-5
min_lr: 0 
weight_decay: 0.0
eval_every: 250 
save_every: 250
log_grads_every: 100
log_lr_every: 10
output_dir: "ckpts/qk_no_norm"
checkpoint: null
lora: false
warmup_steps: 200
num_epochs: 2 
debug: false
scheduler: false

# logging
wandb: true
wandb_entity: gpt4all
wandb_project_name: mem_attn
seed: 42