# model/tokenizer
model_name: "EleutherAI/pythia-12b"
tokenizer_name: "EleutherAI/pythia-12b"
gradient_checkpointing: true
save_name: "nomic-ai/gpt4all-delphi"

# dataset
streaming: false
num_proc: 64
dataset_path: "nomic-ai/gpt4all-j-prompt-generations"
revision: "v1.3-groovy"
max_length: 1024
batch_size: 16

# train dynamics
lr: 2.0e-5
min_lr: 0 
weight_decay: 0.0
eval_every: 500
save_every: 500
log_grads_every: 100
output_dir: ckpts/pythia/
checkpoint: null
lora: false
warmup_steps: 500
num_epochs: 3 

# logging
wandb: true
wandb_entity: gpt4all
wandb_project_name: gpt4all
seed: 42

