# model/tokenizer
model_name: "EleutherAI/pythia-1b"
tokenizer_name: "EleutherAI/pythia-1b"
version: null
gradient_checkpointing: true
save_name: "nomic-ai/lethe"
push_to_hub: false
memory_attn_layer: 12

# dataset
streaming: false
num_proc: 64
dataset_path: "/home/paperspace/gpt4all/gpt4all/index/squad_supplemented_train" 
max_length: 1024
batch_size: 64
pct_test: 0.05
q_column: "question"
a_column: "answers"
context_column: "neighbor_text"
num_memories_per_index: 500000
num_neighbors_to_retrieve: 32
mem_chunk_size: 64

# train dynamics
lr: 1.0e-4
min_lr: 0 
weight_decay: 0.0
eval_every: 100 
save_every: -1
log_grads_every: 100
log_lr_every: 10
output_dir: "ckpts/mem_attn"
checkpoint: null
lora: false
warmup_steps: 500
num_epochs: 5 
debug: false
scheduler: false

# logging
wandb: false
wandb_entity: gpt4all
wandb_project_name: mem_attn
seed: 42

