# model/tokenizer
model_name: "EleutherAI/pythia-1b"
tokenizer_name: "EleutherAI/pythia-1b"
version: null
gradient_checkpointing: true
save_name: "nomic-ai/minipille"
push_to_hub: false
memory_attn_layer: 12

# dataset
streaming: false
num_proc: 64
dataset_path: "pg19"
max_length: 2048
seq_len: 512
segments: 16
batch_size: 16
pct_test: 0.05
num_memories_per_index: 100000
mem_chunk_size: 512
num_neighbors_to_retrieve: 32

# train dynamics
lr: 2.0e-4
min_lr: 0 
weight_decay: 0.0
eval_every: 250 
save_every: -1
log_grads_every: 100
log_lr_every: 10
output_dir: "ckpts/minipile"
checkpoint: null
lora: false
warmup_steps: 500
num_epochs: 5 
debug: false
scheduler: false

# logging
wandb: true
wandb_entity: gpt4all
wandb_project_name: enwik8
seed: 42

