# model/tokenizer
model_name: "EleutherAI/pythia-1b"
tokenizer_name: "EleutherAI/pythia-1b"
version: null
gradient_checkpointing: true
save_name: "nomic-ai/minipille"
push_to_hub: false
memory_attn_layer: 12

# dataset
streaming: false
num_proc: 64
dataset_path: "JeanKaddour/minipile" 
max_length: 2048
batch_size: 64
pct_test: 0.05
num_memories_per_index: 5000000
mem_chunk_size: 512
num_chunks: 10
num_neighbors_to_retrieve: 32

# train dynamics
lr: 1.0e-4
min_lr: 0 
weight_decay: 0.0
eval_every: 100 
save_every: -1
log_grads_every: 100
log_lr_every: 10
output_dir: "ckpts/minipile"
checkpoint: null
lora: false
warmup_steps: 500
num_epochs: 5 
debug: false
scheduler: false

# logging
wandb: true
wandb_entity: gpt4all
wandb_project_name: minipile
seed: 42

